### ISSUE TITLE
2020-03-31 ota nem engedi be kreta a klienst

### ISSUE THREAD

**Issue by zoltansx** [szekelymilan/e-kreta-cli#5]
A kliens oldali config nem valtozott es a reconfigure sem segitett.

```
- Downloading...
Invalid institute in configuration. Please run reconfigure.
✖ An error occured while fetching data.
RequestError: Error: no auth mechanism defined
    at new RequestError (/Users/cselia/Work/e-kreta-cli/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/cselia/Work/e-kreta-cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/cselia/Work/e-kreta-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Auth.onRequest (/Users/cselia/Work/e-kreta-cli/node_modules/request/lib/auth.js:132:18)
    at Request.auth (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:1341:14)
    at Request.init (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:378:10)
    at Request.RP$initInterceptor [as init] (/Users/cselia/Work/e-kreta-cli/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:127:8) {
  name: 'RequestError',
  message: 'Error: no auth mechanism defined',
  cause: Error: no auth mechanism defined
      at Auth.onRequest (/Users/cselia/Work/e-kreta-cli/node_modules/request/lib/auth.js:132:32)
      at Request.auth (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:1341:14)
      at Request.init (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:378:10)
      at Request.RP$initInterceptor [as init] (/Users/cselia/Work/e-kreta-cli/node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:127:8)
      at request (/Users/cselia/Work/e-kreta-cli/node_modules/request/index.js:53:10)
      at Function.get (/Users/cselia/Work/e-kreta-cli/node_modules/request/index.js:61:12)
      at module.exports (/Users/cselia/Work/e-kreta-cli/node_modules/e-kreta-cli/src/assignments.js:20:21)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async doTask (/Users/cselia/Work/e-kreta-cli/node_modules/e-kreta-cli/cli.js:49:7),
  error: Error: no auth mechanism defined
      at Auth.onRequest (/Users/cselia/Work/e-kreta-cli/node_modules/request/lib/auth.js:132:32)
      at Request.auth (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:1341:14)
      at Request.init (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:378:10)
      at Request.RP$initInterceptor [as init] (/Users/cselia/Work/e-kreta-cli/node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (/Users/cselia/Work/e-kreta-cli/node_modules/request/request.js:127:8)
      at request (/Users/cselia/Work/e-kreta-cli/node_modules/request/index.js:53:10)
      at Function.get (/Users/cselia/Work/e-kreta-cli/node_modules/request/index.js:61:12)
      at module.exports (/Users/cselia/Work/e-kreta-cli/node_modules/e-kreta-cli/src/assignments.js:20:21)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async doTask (/Users/cselia/Work/e-kreta-cli/node_modules/e-kreta-cli/cli.js:49:7),
  options: {
    auth: { bearer: undefined },
    uri: 'https://klik034895001.e-kreta.hu/mapi/api/v1/Lesson',
    method: 'GET',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

```

**Comment by zoltansx** [comment]
Tegnap volt kreta kliens update, vsz. valami valtozott az api-ban

**Comment by zoltansx** [comment]
vscode-dal ramentem, sok minden nem derult ki:
```
e
RequestError {name: "RequestError", message: "Error: read ECONNRESET", cause: Error: read ECONNRESET
    at TLSWrap.onStreamRead…, error: Error: read ECONNRESET
    at TLSWrap.onStreamRead…, options: Object, …}

e.stack
"RequestError: Error: read ECONNRESET
    at new RequestError (e-kreta-cli/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (e-kreta-cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (e-kreta-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (e-kreta-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (e-kreta-cli/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)"

e.cause
Error: read ECONNRESET

e.cause.errno
-54

e.cause.syscall
"read"

e.options.body
"institute_code=klik034895001&userName=XXXX&password=XXXX&grant_type=password&client_id=919e0c1c-76a2-4646-a2fb-7085bbbf3c56"

e.options.uri
"https://klik034895001.e-kreta.hu/idp/api/v1/Token"

```

**Comment by szekelymilan** [comment]
Köszi, hogy jelezted! :smiley:
Meg fogom nézni, amint lesz rá időm.

**Comment by zoltansx** [comment]
Van egy másik e-kreta kliens, ami hétfő óta fixelve lett, és ott van egy commit, ami új useragentet állítbe, tippeim szerint ez lesz a kulcs:

https://github.com/Coware-Apps/ellenorzo/commit/3c9e946dc5403986232596ec4011371198ae51c4#diff-a8e517eb53b3d8ddba6374baa790f164L258

: 

`let userAgent = 'Kreta.Ellenorzo/2.9.9.2020022101 (Android 0.0)'
`

Sajnos nem kodolok js-ben és nem találtam a kódban hol kell beállítani a useragentet.

**Comment by zoltansx** [comment]
Itt a fix ☺ 
https://github.com/zoltansx/e-kreta-cli/tree/ua_fix

**Comment by szekelymilan** [comment]
Köszi! 😃
Este frissítem a repoban.

**Comment by szekelymilan** [comment]
Elnézést a késői fixért, cserébe még **javítottam pár dolgot**. Teszteld kérlek. 😄

**Comment by zoltansx** [comment]
Teszteltem, műxik 👍 , bár most az összes régi HF előkerült, még tavalyiak is!. Sebaj, git repo-ban vannak a házik, tudom követni 😄

**Comment by szekelymilan** [comment]
Tervezek egy olyan **optiont hozzáadni**, amellyel kiválasztható a **letöltendő időintervallum**.
Ez a #4 issue esetében is **fontos lehet**.
